// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlzjoasyheqykokiljwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsempvYXN5aGVxeWtva2lsandqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMjA3MzEsImV4cCI6MjA2MjY5NjczMX0.gMMEB8Bw-ACU0FPQBT-XrOVDllHfPuFPJCN7T6lcGTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);